<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model\Transaction\Schema;

/**
 * Schema class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Schema{
    private $schemaDefinition; //array SchemaAttribute

    public function __construct($schemaDefinition){
        $this->schemaDefinition = $schemaDefinition;
    }

    public function serialize($bytes) {
        $resultBytes = array();
        $arr = $this->schemaDefinition;
        //$tmp = $this->schemaDefinition[0]->serialize($bytes, 4 + (0 * 2));
        for ($i=0;$i<count($arr);++$i) {
            $tmp = $this->schemaDefinition[$i]->serialize($bytes, 4 + ($i * 2));
            $resultBytes = array_merge($resultBytes, $tmp);
        }
        return $resultBytes;
    }
}
?>