<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * AccountPropertyDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountPropertyDTO{

    private $propertyType;//AccountPropertyTypeEnum

    private $values;//array UInt64DTO, String, integer

    public function __construct($data){
        $this->propertyType = $data["propertyType"];
        $this->values = $data["values"];
    }

    public function getPropertyType(){
        return $this->propertyType;
    }

    public function getValues(){
        return $this->values;
    }
}
