<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * AccountPropertiesInfoDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountNamesDTO{

    private $address; //string
    private $names; //array

    public function __construct($data){
        $this->address = $data["address"];
        $this->names = $data["names"];
    }

    public function getAddress(){
        return $this->address;
    }
    public function getNames(){
        return $this->names;
    }
}
