<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * AccountPropertyTypeEnum class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountPropertyTypeEnum
{    
    /**
     * @internal
     * @var integer
     */
    const ALLOW_ADDRESS = "01"; //1

    /**
     * @internal
     * @var integer
     */
    const ALLOW_MOSAIC = "02"; //2

    /**
     * @internal
     * @var integer
     */
    const ALLOW_TRANSACTION = "04"; //4

    /**
     * @internal
     * @var integer
     */
    const SENTINEL = "05"; //5

    /**
     * @internal
     * @var integer
     */
    const BLOCK_ADDRESS = "81"; //129

    /**
     * @internal
     * @var integer
     */
    const BLOCK_MOSAIC = "82"; //130

    /**
     * @internal
     * @var integer
     */
    const BLOCK_TRANSACTION = "84"; //132

}
