<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * AccountPropertyModification class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountPropertyModification{

    private $type;//AccountPropertiesModificationTypeEnum

    private $value;//array string or UInt64DTO or int

    public function __construct($type, $value){
        $this->type = $type;
        $this->value = $value;
    }

    public function getType(){
        return $this->type;
    }

    public function getValue(){
        return $this->value;
    }
}
?>