<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * AddressAliasTransactionDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressAliasTransactionDTO extends TransactionDTO{

    private $aliasAction;//AliasActionEnum

    private $namespaceId;//UInt64DTO

    private $address;//hex string

    public function __construct($data){
        $this->signature = $data["signature"];
        $this->signer = $data["signer"];
        $this->version = $data["version"];
        $this->type = $data["type"];
        $this->maxFee = $data["maxFee"];
        $this->deadline = $data["deadline"];
        $this->aliasAction = $data["aliasAction"];
        $this->namespaceId = $data["namespaceId"];
        $this->address = $data["address"];
    }

    public function getAliasAction(){
        return $this->aliasAction;
    }

    public function getNamespaceId(){
        return $this->namespaceId;
    }

    public function getAddress(){
        return $this->address;
    }
}
