<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

/**
 * BlockchainStorageInfo Class Doc Comment
 *
 * @category Class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BlockchainStorageInfo{
    private $numBlocks;

    private $numTransactions;

    private $numAccounts;

    public function __construct($numBlocks, $numTransactions, $numAccounts){
        $this->numBlocks = $numBlocks;
        $this->numTransactions = $numTransactions;
        $this->numAccounts = $numAccounts;
    }

    public function getNumBlocks(){
        return $this->numBlocks;
    }

    public function getNumTransactions(){
        return $this->numTransactions;
    }

    public function getNumAccounts(){
        return $this->numAccounts;
    }
}


