<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

$defaultRepConfig = array(
    "minInteractions" => 10,
    "defaultReputation" => 0.9,
);

/**
 * Config class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Config{
    protected $WebsocketReconnectionDefaultTimeout = 5000; //5s
    protected $defaultRepConfig = array(
        "minInteractions" => 10,
        "defaultReputation" => 0.9,
    );

    // returns config for HTTP Client from passed node url and network type
    public function NewConfig($baseUrl,$networkType ,$wsReconnectionTimeout){
        if ($wsReconnectionTimeout == 0) {
            $wsReconnectionTimeout = $this->WebsocketReconnectionDefaultTimeout;
        }
        $confDef = (object)$this->defaultRepConfig;
        $resovle = $this->NewConfigWithReputation($baseUrl, $networkType, $confDef, $wsReconnectionTimeout);
        return $resovle;
    }

    public function NewConfigWithReputation($baseUrl, $networkType, $confDef, $wsReconnectionTimeout){
        if (strlen($baseUrl) == 0) {
            throw new Exception("empty base urls");
        }
        $c = array(
            "BaseURL" => $baseUrl,
            "WsReconnectionTimeout" => $wsReconnectionTimeout,
            "NetworkType" => $networkType,
            "reputationConfig" =>  $confDef,
        );
        return (object)$c;
    }
}