<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * EmbeddedRegisterNamespaceTransactionDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmbeddedRegisterNamespaceTransactionDTO extends EmbeddedTransactionDTO{

    private $namespaceType; //NamespaceTypeEnum

    private $duration; //UInt64DTO

    private $namespaceId; //UInt64DTO

    private $name; //string

    private $parentId; //UInt64DTO

    public function __construct($dataArray){
        $this->signer = $dataArray["signer"];
        $this->version = $dataArray["version"];
        $this->type = $dataArray["type"];
        $this->namespaceType = $dataArray["namespaceType"];
        $this->duration = $dataArray["duration"];
        $this->namespaceId = $dataArray["namespaceId"];
        $this->name = $dataArray["name"];
        $this->parentId = $dataArray["parentId"];
    }

    public function getNamespaceType(){
        return $this->namespaceType;
    }

    public function getDuration(){
        return $this->duration;
    }

    public function getNamespaceId(){
        return $this->namespaceId;
    }

    public function getName(){
        return $this->name;
    }

    public function getParentId(){
        return $this->parentId;
    }

}
