<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * EmbeddedTransactionMetaDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmbeddedTransactionMetaDTO {
    
    private $height; //UInt64DTO

    private $aggregateHash; //string

    private $aggregateId; //string

    private $index; //int

    private $id; //string

    public function __construct($dataArray){
        $this->height = $dataArray["height"];
        $this->aggregateHash = $dataArray["aggregateHash"];
        $this->aggregateId = $dataArray["aggregateId"];
        $this->index = $dataArray["index"];
        $this->id = $dataArray["id"];
    }

    public function getHeight(){
        return $this->height;
    }

    public function getAggregateHash(){
        return $this->aggregateHash;
    }

    public function getAggregateId(){
        return $this->aggregateId;
    }

    public function getIndex(){
        return $this->index;
    }

    public function getId(){
        return $this->id;
    }
}


