<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;
use Proximax\Utils\Utils;
use Proximax\Model\UInt64DTO;

/**
 * BlockMetaDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LockDTO {

    private $account; //number

    private $accountAddress;//string

    private $mosaicId;//string

    private $amount; //string

    private $height;//array

    private $status; //int

    private $hash; //string

    private $hashAlgorithm; //int

    private $secret; //int

    private $recipient; //string

    private $compositeHash; //string

    public function __construct($data){
        $this->account = $data->account;
        $this->accountAddress = $data->accountAddress;
        $this->mosaicId = $data->mosaicId;
        $this->amount = $data->amount;
        $this->height = $data->height;
        $this->status = $data->status;
        $this->hash = $data->hash;
        $this->hashAlgorithm = $data->hashAlgorithm;
        $this->secret = $data->secret;
        $this->recipient = $data->recipient;
        $this->compositeHash = $data->compositeHash;
    }

    public function getAccount(){
        return $this->account;
    }

    public function getCompositeHash(){
        return $this->compositeHash;
    }

    public function getAccountAddress(){
        return $this->accountAddress;
    }

    public function getMosaicId(){
        return $this->mosaicId;
    }

    public function getAmount(){
        return $this->amount;
    }

    public function getHeight(){
        return $this->height;
    }

    public function getStatus(){
        return $this->status;
    }

    public function getHash(){
        return $this->hash;
    }

    public function getSecret(){
        return $this->secret;
    }

    public function getRecipient(){
        return $this->recipient;
    }

    public function getHashAlgorithm(){
        return $this->hashAlgorithm;
    }
}
?>