<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;
use Proximax\Utils\Utils;

/**
 * MaxFee class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MaxFee{
    public $maxFee; //array

    public function __construct($maxFee){
        if (is_array($maxFee)){
            $this->maxFee = $maxFee;
        }
        else if (is_numeric($maxFee)){
            $utils = new Utils;
            $this->fee_array = $utils->fromBigInt($maxFee);
        }
        else return "Wrong fee format";
    }

    public function getFeeValue(){
        return (($maxFee[1] << 32) | ($maxFee[0]));
    }


}
?>