<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * ModifyMultisigAccountTransactionDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModifyMultisigAccountTransactionDTO extends TransactionDTO{

    private $minRemovalDelta; //int

    private $minApprovalDelta; //int
  
    private $modifications; //array CosignatoryModificationDTO

    public function __construct($data){
        $this->signature = $data["signature"];
        $this->signer = $data["signer"];
        $this->version = $data["version"];
        $this->type = $data["type"];
        $this->maxFee = $data["maxFee"];
        $this->deadline = $data["deadline"];
        $this->minRemovalDelta = $data["minRemovalDelta"];
        $this->minApprovalDelta = $data["minApprovalDelta"];
        $this->modifications = $data["modifications"];
    }

    public function getMinRemovalDelta(){
        return $this->minRemovalDelta;
    }
    
    public function getMinApprovalDelta(){
        return $this->minApprovalDelta;
    }

    public function getModifications(){
        return $this->modifications;
    }
}