<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

use \ArrayAccess;
use \NEM\ObjectSerializer;

/**
 * MosaicDefinitionDTO Class Doc Comment
 *
 * @category Class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MosaicDefinitionDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MosaicDefinitionDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'namespaceId' => '\NEM\Model\UInt64DTO',
        'mosaicId' => '\NEM\Model\UInt64DTO',
        'supply' => '\NEM\Model\UInt64DTO',
        'height' => '\NEM\Model\UInt64DTO',
        'owner' => 'string',
        'properties' => '\NEM\Model\MosaicPropertiesDTO',
        'levy' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'namespaceId' => null,
        'mosaicId' => null,
        'supply' => null,
        'height' => null,
        'owner' => null,
        'properties' => null,
        'levy' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'namespaceId' => 'namespaceId',
        'mosaicId' => 'mosaicId',
        'supply' => 'supply',
        'height' => 'height',
        'owner' => 'owner',
        'properties' => 'properties',
        'levy' => 'levy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'namespaceId' => 'setNamespaceId',
        'mosaicId' => 'setMosaicId',
        'supply' => 'setSupply',
        'height' => 'setHeight',
        'owner' => 'setOwner',
        'properties' => 'setProperties',
        'levy' => 'setLevy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'namespaceId' => 'getNamespaceId',
        'mosaicId' => 'getMosaicId',
        'supply' => 'getSupply',
        'height' => 'getHeight',
        'owner' => 'getOwner',
        'properties' => 'getProperties',
        'levy' => 'getLevy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['namespaceId'] = isset($data['namespaceId']) ? $data['namespaceId'] : null;
        $this->container['mosaicId'] = isset($data['mosaicId']) ? $data['mosaicId'] : null;
        $this->container['supply'] = isset($data['supply']) ? $data['supply'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['owner'] = isset($data['owner']) ? $data['owner'] : null;
        $this->container['properties'] = isset($data['properties']) ? $data['properties'] : null;
        $this->container['levy'] = isset($data['levy']) ? $data['levy'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['namespaceId'] === null) {
            $invalidProperties[] = "'namespaceId' can't be null";
        }
        if ($this->container['mosaicId'] === null) {
            $invalidProperties[] = "'mosaicId' can't be null";
        }
        if ($this->container['supply'] === null) {
            $invalidProperties[] = "'supply' can't be null";
        }
        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        if ($this->container['owner'] === null) {
            $invalidProperties[] = "'owner' can't be null";
        }
        if ($this->container['properties'] === null) {
            $invalidProperties[] = "'properties' can't be null";
        }
        if ($this->container['levy'] === null) {
            $invalidProperties[] = "'levy' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['namespaceId'] === null) {
            return false;
        }
        if ($this->container['mosaicId'] === null) {
            return false;
        }
        if ($this->container['supply'] === null) {
            return false;
        }
        if ($this->container['height'] === null) {
            return false;
        }
        if ($this->container['owner'] === null) {
            return false;
        }
        if ($this->container['properties'] === null) {
            return false;
        }
        if ($this->container['levy'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets namespaceId
     *
     * @return \NEM\Model\UInt64DTO
     */
    public function getNamespaceId()
    {
        return $this->container['namespaceId'];
    }

    /**
     * Sets namespaceId
     *
     * @param \NEM\Model\UInt64DTO $namespaceId namespaceId
     *
     * @return $this
     */
    public function setNamespaceId($namespaceId)
    {
        $this->container['namespaceId'] = $namespaceId;

        return $this;
    }

    /**
     * Gets mosaicId
     *
     * @return \NEM\Model\UInt64DTO
     */
    public function getMosaicId()
    {
        return $this->container['mosaicId'];
    }

    /**
     * Sets mosaicId
     *
     * @param \NEM\Model\UInt64DTO $mosaicId mosaicId
     *
     * @return $this
     */
    public function setMosaicId($mosaicId)
    {
        $this->container['mosaicId'] = $mosaicId;

        return $this;
    }

    /**
     * Gets supply
     *
     * @return \NEM\Model\UInt64DTO
     */
    public function getSupply()
    {
        return $this->container['supply'];
    }

    /**
     * Sets supply
     *
     * @param \NEM\Model\UInt64DTO $supply supply
     *
     * @return $this
     */
    public function setSupply($supply)
    {
        $this->container['supply'] = $supply;

        return $this;
    }

    /**
     * Gets height
     *
     * @return \NEM\Model\UInt64DTO
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param \NEM\Model\UInt64DTO $height height
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return string
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param string $owner owner
     *
     * @return $this
     */
    public function setOwner($owner)
    {
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return \NEM\Model\MosaicPropertiesDTO
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param \NEM\Model\MosaicPropertiesDTO $properties properties
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->container['properties'] = $properties;

        return $this;
    }

    /**
     * Gets levy
     *
     * @return object
     */
    public function getLevy()
    {
        return $this->container['levy'];
    }

    /**
     * Sets levy
     *
     * @param object $levy levy
     *
     * @return $this
     */
    public function setLevy($levy)
    {
        $this->container['levy'] = $levy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


