<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * MosaicPropertyId class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MosaicPropertyId{
    const FLAGS = 0;
    const DIVISIBILITY = 1;
    const DURATION = 2;

    private $code;

    public function __construct($code){
        $this->code = $code;
    }

    public function getCode(){
        return $this->code;
    }
    
}