<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;
use Proximax\Utils\Utils;

/**
 * MosaicDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MosaicDTO{
    
    private $id; //UInt64DTO

    private $amount;//UInt64DTO

    public function __construct($id, $amount){
        $this->id = $id;
        $this->amount = $amount;
    }

    public function getId(){
        return  $this->id;
    }

    public function getAmount(){
        return  $this->amount;
    }
}


