<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

use Proximax\Utils\Utils;
use Proximax\Model\NamespaceId;

/**
 * Mosaic class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Mosaic{

    public $id; //big Int

    public $amount;//big Int

    public function __construct($id = null,int $amount = null){
        $utils = new Utils;
        if ($id === null || $id == "xpx"){
            $this->id = array(481110499,231112638); //xpx id
        }
        else if (is_string($id)){
            $this->id = $utils->fromBigInt(hexdec($id));
        }
        else if (is_array($id)){
            $this->id = $id;
        }
        else if ($id instanceof NamespaceId){
            $this->id = $id->getId();
        }
        else throw new \Exception("Wrong mosaic id");
        
        if ($amount === null){
            $this->amount = array(0,0);
        }
        else {
            $this->amount = $utils->fromBigInt($amount);
        }
    }

    public function getId(){
        return $this->id;
    }

    public function getAmount(){
        return $this->amount;
    }
    
    public function getIdValue(){
        $utils = new Utils;
        return $utils->bigIntToHexString($this->id);
    }

    public function getAmountValue(){
        return  ($this->amount[1] << 32) | $this->amount[0];
    }
}
