<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

/**
 * MultisigCosignatoryModificationType class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MultisigCosignatoryModificationType
{    
    /**
     * @internal
     * @var integer
     */
    const ADD = 0;

    /**
     * @internal
     * @var integer
     */
    const REMOVE = 1;

}
