<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

/**
 * MultisigCosignatoryModification class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MultisigCosignatoryModification{
    private $type;

    private $publicAccount;

    public function __construct($type, $publicAccount){
        $this->type = $type;
        $this->publicAccount = $publicAccount;
    }

    public function getType(){
        return $this->type;
    }

    public function getPublicAccount(){
        return $this->publicAccount;
    }
}
?>