<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;


/**
 * NamespaceId Class Doc Comment
 *
 * @category Class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NamespaceId{
    private $id; //bigInt

    private $string;

    public function __construct($id){
        $this->id = $id;

        $str1 = dechex($id[0]);
        if (strlen($str1) < 8){
            for ($i=0;$i<8-strlen($str1);$i++){
                $str1 = "0" . $str1;
            }
        }
        $str2 = dechex($id[1]);
        if (strlen($str2) < 8){
            for ($i=0;$i<8-strlen($str2);$i++){
                $str2 = "0" . $str2;
            }
        }
        $this->string = strtoupper($str2 . $str1);
    }

    public function getId(){
        return $this->id;
    }

    public function getString(){
        return $this->string;
    }

}


