<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * NamespaceDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NamespaceDTO{

    private $owner;//string

    private $ownerAddress;//string

    private $startHeight;//UInt64DTO

    private $endHeight;//UInt64DTO

    private $depth;//int

    private $level0;//UInt64DTO

    private $level1;//[option] UInt64DTO

    private $level2;//[option] UInt64DTO

    private $type;//NamespaceTypeEnum

    private $alias;//AliasDTO

    private $parentId;//UInt64DTO

    public function __construct($data){
        $this->owner = $data["owner"];
        $this->ownerAddress = $data["ownerAddress"];
        $this->startHeight = $data["startHeight"];
        $this->endHeight = $data["endHeight"];
        $this->depth = $data["depth"];
        $this->level0 = $data["level0"];
        $this->level1 = $data["level1"];
        $this->level1 = $data["level2"];
        $this->type = $data["type"];
        $this->alias = $data["alias"];
        $this->parentId = $data["parentId"];
    }

    public function getOwner(){
        return $this->owner;
    }

    public function getOwnerAddress(){
        return $this->ownerAddress;
    }

    public function getStartHeight(){
        return $this->startHeight;
    }

    public function getEndHeight(){
        return $this->endHeight;
    }

    public function getDepth(){
        return $this->depth;
    }

    public function getLevel0(){
        return $this->level0;
    }

    public function getLevel1(){
        return $this->level1;
    }

    public function getLevel2(){
        return $this->level2;
    }

    public function getType(){
        return $this->type;
    }

    public function getAlias(){
        return $this->alias;
    }

    public function getParentId(){
        return $this->parentId;
    }
}
