<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * EntityDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaginationDTO{

    private $pageNumber;//int

    private $pageSize;//pageSize


    public function __construct($data){
        $this->pageNumber = $data["pageNumber"];
        $this->pageSize = $data["pageSize"];
    }

    public function getPageNumber(){
        return $this->pageNumber;
    }

    public function getPageSize(){
        return $this->pageSize;
    }

}