<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * ReceiptDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReceiptDTO{

    protected $version; //int

    protected $type; //ReceiptTypeEnum

    public function __construct($dataArray){
        $this->version = $dataArray["version"];
        $this->type = $dataArray["type"];
    }

    public function getVersion(){
        return $this->version;
    }

    public function getType(){
        return $this->type;
    }

}
