<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * ReceiptTypeEnum class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReceiptTypeEnum
{    
    /**
     * @internal
     * @var integer
     */
    const NUMBER_4685 = 4685;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_4941 = 4941;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_4686 = 4686;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_8515 = 8515;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_8776 = 8776;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_9042 = 9042;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_12616 = 12616;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_12626 = 12626;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_16717 = 16717;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_16718 = 16718;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_20803 = 20803;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_57652 = 57652;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_61763 = 61763;

    /**
     * @internal
     * @var integer
     */
    const NUMBER_62019 = 62019;

}
