<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * ResolutionStatementDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResolutionStatementDTO{

    private $height; //UInt64DTO

    private $unresolved; //UInt64DTO

    private $resolutionEntries; //array ResolutionEntryDTO

    public function __construct($dataArray){
        $this->height = $dataArray["height"];
        $this->unresolved = $dataArray["unresolved"];
        $this->resolutionEntries = $dataArray["resolutionEntries"];
    }

    public function getHeight(){
        return $this->height;
    }

    public function getUnresolved(){
        return $this->unresolved;
    }

    public function getResolutionEntries(){
        return $this->resolutionEntries;
    }

}
