<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * SignedTransaction class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SignedTransaction{
    public $type;

    public $payload;

    public $hash;

    public function __construct($type, $payload, $hash){
        $this->type = $type;
        $this->payload = $payload;
        $this->hash = $hash;
    }

    public function getType(){
        return $this->type;
    }

    public function getPayload(){
        return $this->payload;
    }

    public function getHash(){
        return $this->hash;
    }
}
?>