<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

/**
 * TransactionInfo class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionInfo{

    private $height; //HeightDTO

    private $index; //int

    private $id; //string

    private $hash; //string

    private $merkleComponentHash;//string

    private $aggregateHash;//string

    private $aggregateId;//string


    public function __construct($height = null, $index = null, $id = null, $hash = null, 
                                $merkleComponentHash = null, $aggregateHash = null, $aggregateId = null){
        if($height !== null){
            $this->height = $height;
        }
        else  $this->height = array();

        if ($index !== null){
            $this->index = $index;
        }
        else $this->index = null;

        if ($id !== null){
            $this->id = $id;
        }
        else $this->id = null;

        if ($hash !== null){
            $this->hash = $hash;
        }
        else $this->hash = null;

        if ($merkleComponentHash !== null){
            $this->merkleComponentHash = $merkleComponentHash;
        }
        else $this->merkleComponentHash = null;

        if ($aggregateHash !== null){
            $this->aggregateHash = $aggregateHash;
        }
        else $this->aggregateHash = null;

        if ($aggregateId !== null){
            $this->aggregateId = $aggregateId;
        }
        else $this->aggregateId = null;
    }

    public function getHeight(){
        return $this->height;
    }

    public function getIndex(){
        return $this->index;
    }

    public function getId(){
        return $this->id;
    }

    public function getHash(){
        return $this->hash;
    }

    public function getMerkleComponentHash(){
        return $this->merkleComponentHash;
    }

    public function getAggregateHash(){
        return $this->aggregateHash;
    }

    public function getAggregateId(){
        return $this->aggregateId;
    }

    public function setHash($hash){
        return $this->hash = $hash;
    }
}
?>