<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model;

/**
 * TransactionDTO class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionDTO{
    private $AbstractTransaction; //object

    private $Mosaics; //array Mosaic

    private $Recipient; //Address

    private $Message; //Message

    public function __construct($arrayData){
        $this->AbstractTransaction = $arrayData["AbstractTransaction"];
        $this->Mosaics = $arrayData["Mosaics"];
        $this->Recipient = $arrayData["Recipient"];
        $this->Message = $arrayData["Message"];
    }

    public function getAbstractTransaction(){
        return $this->AbstractTransaction;
    }

    public function getMosaics(){
        return $this->Mosaics;
    }

    public function getRecipient(){
        return $this->Recipient;
    }

    public function getMessage(){
        return $this->Message;
    }
}
?>