<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model;

/**
 * TransactionDTO class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionDTO{

    protected $signature;//String

    protected $signer;//String

    protected $version;//NetworkTypeEnum

    protected $type;//EntityTypeEnum

    protected $maxFee;//UInt64DTO

    protected $deadline;//UInt64DTO

    public function getSignature(){
        return $this->signature;
    }

    public function getSigner(){
        return $this->signer;
    }

    public function getVersion(){
        return $this->version;
    }

    public function getType(){
        return $this->type;
    }

    public function getMaxFee(){
        return $this->maxFee;
    }

    public function getDeadline(){
        return $this->deadline;
    }

}
