<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Sdk;

use Proximax\API\ConfigRoutesApi;
use Proximax\ApiClient;
use Base32\Base32;
use Proximax\Model\UInt64DTO;
use Proximax\Model\CatapultConfigDTO;
use Proximax\Model\ConfigDTO;

/**
 * Config class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Config{
    /**
     *
     * @param config $config
     *
     * @param $publicKey
     * 
     * @return CatapultConfigDTO
     */
    public function GetConfigByHeight($config, $publicKey){
        $ConfigRoutesApi = new ConfigRoutesApi;
        $ApiClient = new ApiClient;
        $url = $config->BaseURL;
        $ApiClient->setHost($url);
        $networkType = $config->NetworkType;

        $data = $ConfigRoutesApi->getConfigByHeight($publicKey);
        if ($data[1] == 200){ // successfull
            $config = new ConfigDTO($this->formatData($data[0]));
            return new CatapultConfigDTO($config);
        }
        return null;
    }

    /**
     *
     * @param object $data
     * 
     * @return ConfigDTO
     */
    private function formatData($data){
        $height = new UInt64DTO($data->catapultConfig->height);
        $blockChainConfig = $data->catapultConfig->blockChainConfig;
        $supportedEntityVersions = $data->catapultConfig->supportedEntityVersions;
        
        $configDTO = array(
            "height" => $height,
            "blockChainConfig" => $blockChainConfig,
            "supportedEntityVersions" => $supportedEntityVersions,
        );
        return $configDTO;
    }
}
?>