<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Model\Transaction\Attribute;

/**
 * ScalarAttribute class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScalarAttribute extends SchemaAttribute {
    private $size;

    public function __construct($name, $typeSize) {
        parent::__construct($name);
        $this->size = $typeSize;
    }

    protected function serialize3Params($buffer, $position, $innerObjectPosition) {
        return $this->findParam($innerObjectPosition, $position, $buffer, $this->size);
    }
}
?>