<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Contracts;

/**
 * Serializable interface Doc Comment
 *
 * @category interface
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface Serializable
{
    /**
     * Serializable::serialize()
     * 
     * This method should return a *byte-array* with UInt8
     * representation of bytes for the said object.
     * 
     * Each class implementing this interface should provide
     * with a specific *serializing process* where the data
     * is grouped and organized correctly according to the 
     * NIS reference.
     * 
     * @param   null|mixed  $parameters     Any parameters you want to pass along to the serialization process.
     * @return  array   Returns a byte-array with values in UInt8 representation.
     */
    public function serialize($parameters = null);
}
