<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace NEM\Core;

use NEM\Contract\KeyPair as KeyPairContract;
use NEM\Core\Buffer;
use NEM\Core\Encoder;
use NEM\Core\Encryption;
use \ParagonIE_Sodium_Core_Ed25519;

/**
 * KeyGenerator class Doc Comment
 *
 * @category class
 * @package  NEM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeyGenerator
{
    /**
     * Derive the public key from the KeyPair's secret.
     *
     * This method uses Keccak 64 bytes (512 bits) hashing on
     * the provided `keyPair`'s secret key.
     *
     * @param   \NEM\Core\KeyPair   $keyPair    The initialized key pair from which to derive the public key.
     * @return  \NEM\Core\Buffer
     */
    public function derivePublicKey(KeyPair $keyPair)
    {
        $buffer = new Buffer;

        // hash the secret key with Keccak SHA3 variation with 512-bit output (64 bytes)
        $new = unpack('C*', $keyPair->getSecretKey()->getBinary());
        $byteArray = $this->toByteArray($new);
        $str = implode(array_map("chr", $byteArray));
        $hashedSecret = Encryption::hash("sha3-512", $str, true); // raw=truehas

        // clamp bits of the scalar *before* scalar multiplication
        $safeSecret = Buffer::clampBits($hashedSecret);

        // do scalar multiplication for: `basePoint` * `safeSecret`
        // the result of this multiplication is the `publicKey`.
        // sk_to_pk() does scalarmult_base() and ge_p3_tobytes()
        $publicKey = ParagonIE_Sodium_Core_Ed25519::sk_to_pk($safeSecret);
        $publicBuf = new Buffer($publicKey, SODIUM_CRYPTO_SIGN_PUBLICKEYBYTES);

        assert(SODIUM_CRYPTO_SIGN_PUBLICKEYBYTES === $publicBuf->getSize());
        return $publicBuf;
    }
    private function toByteArray($array){
        $newArray = array();
        $lenNum = count($array);
        for ($i=0;$i<$lenNum;$i++){
            if ($array[$lenNum-$i] > 128){
                $newArray[$i] = $array[$lenNum-$i] - 256;
            }
            else $newArray[$i] = $array[$lenNum-$i];
        }
        return $newArray;
    } 
}
