<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Core;

use Proximax\Core\Buffer;

/**
 * Ripemd160Hasher class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Ripemd160Hasher
{
    /**
     * Non-Incremental RIPEMD160 Hash implementation.
     * 
     * @param   string|\Proximax\Core\Buffer $data           The data that needs to be hashed.
     * @param   boolean                 $raw_output     Whether to return raw data or a Hexadecimal hash.
     * @return  string
     */
    static public function hash($data, $raw_output = false)
    {
        // use PHP implementation of sha3
        return hash("ripemd160", $data, (bool) $raw_output);
    }
}
