<?php
/**
 * NIS2 API
 *
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: greg@evias.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 * 
 */

namespace Proximax\Model\Transaction;
use Proximax\Model\TransactionType;
use Proximax\Model\Deadline;
use Proximax\Model\TransactionVersion;
use Proximax\Model\TransactionInfo;
use Proximax\Model\PublicAccount;
use Proximax\Infrastructure\Network;
use Proximax\Model\Transaction\Schema\MosaicSupplyChangeTransactionSchema;
use \Google\FlatBuffers\FlatbufferBuilder;
use \Catapult\Buffers\MosaicSupplyChangeTransactionBuffer;
use Proximax\Utils\Hex;
use Proximax\Utils\Utils;
use Proximax\Model\AbstractTransaction;
use Proximax\Model\Transaction\IdGenerator;

/**
 * MosaicSupplyChangeTransaction class Doc Comment
 *
 * @category class
 * @package  Proximax
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MosaicSupplyChangeTransaction extends \Proximax\Model\Transaction{

    private $mosaicId; //MosaicId

    private $mosaicSupplyType; //MosaicSupplyTpe

    private $delta; //bigInt
     
    public function __construct($deadline, $mosaicId, $mosaicSupplyType, $duration, $networkType){
        $version = TransactionVersion::MOSAIC_SUPPLY_CHANGE_VERSION;
        $type = hexdec(TransactionType::MOSAIC_SUPPLY_CHANGE);
        if (is_string($networkType) && in_array(strtolower($networkType), ["mijin", "mijintest", "public", "publictest", "private", "privatetest", "NotSupportedNet", "aliasaddress"])){
            $networkType = Network::$networkInfos[strtolower($networkType)]["id"];
        }
        else if (is_numeric($networkType) && !in_array($networkType, [96, 144, 184, 168, 200, 176, 0, 145])) {
            throw new NISInvalidNetworkId("Invalid netword ID '" . $networkType . "'");
        } 
        $maxFee = array(0,0);
        $signature = ""; 
        $signer = new PublicAccount;
        $transactionInfo = new TransactionInfo;

        $abstractTransaction = new AbstractTransaction($transactionInfo,$deadline,$networkType,
                                                    $type,$version,$maxFee,$signature,$signer);
        $this->setAbstractTransaction($abstractTransaction);

        $this->mosaicId = $mosaicId;
        $this->mosaicSupplyType = $mosaicSupplyType;
        $this->delta = $duration;
    }

    public function generateBytes() {
        $networkType = $this->getAbstractTransaction()->getNetworkType();
        $version = $this->getAbstractTransaction()->getVersion();
        $deadline = $this->getAbstractTransaction()->getDeadline();
        $signature = $this->getAbstractTransaction()->getSignature();
        $signer = $this->getAbstractTransaction()->getSigner();
        $maxFee = $this->getAbstractTransaction()->getMaxFee();
        $type = $this->getAbstractTransaction()->getType();

        $mosaicId = $this->mosaicId;
        $mosaicSupplyType = $this->mosaicSupplyType;
        $delta = $this->delta;

        $builder = new FlatbufferBuilder(1);
        
        $v = ($networkType << 24) + $version;

        // Create Vectors
        $signatureVector = MosaicSupplyChangeTransactionBuffer::createSignatureVector($builder, (new Utils)->createArrayZero(64));
        $signerVector = MosaicSupplyChangeTransactionBuffer::createSignerVector($builder, (new Utils)->createArrayZero(32));
        $deadlineVector = MosaicSupplyChangeTransactionBuffer::createDeadlineVector($builder, $deadline->getTimeArray());
        $feeVector = MosaicSupplyChangeTransactionBuffer::createMaxFeeVector($builder, $maxFee);
        
        $mosaicIdVector = MosaicSupplyChangeTransactionBuffer::createMosaicIdVector($builder,$mosaicId->getId());
        $deltaVector = MosaicSupplyChangeTransactionBuffer::createDeltaVector($builder,$delta);

        // header, mosaic id, supply type, delta
        $size = self::HEADER_SIZE + 8 + 1 + 8;

        MosaicSupplyChangeTransactionBuffer::startMosaicSupplyChangeTransactionBuffer($builder);
        MosaicSupplyChangeTransactionBuffer::addSize($builder, $size);
        MosaicSupplyChangeTransactionBuffer::addSignature($builder, $signatureVector);
        MosaicSupplyChangeTransactionBuffer::addSigner($builder, $signerVector);
        MosaicSupplyChangeTransactionBuffer::addVersion($builder, $v);
        MosaicSupplyChangeTransactionBuffer::addType($builder, $type);
        MosaicSupplyChangeTransactionBuffer::addMaxFee($builder, $feeVector);
        MosaicSupplyChangeTransactionBuffer::addDeadline($builder, $deadlineVector);

        MosaicSupplyChangeTransactionBuffer::addMosaicId($builder, $mosaicIdVector);
        MosaicSupplyChangeTransactionBuffer::addDirection($builder, $mosaicSupplyType);
        MosaicSupplyChangeTransactionBuffer::addDelta($builder, $deltaVector);
        
        $codedTransaction = MosaicSupplyChangeTransactionBuffer::endMosaicSupplyChangeTransactionBuffer($builder);
        
        $builder->finish($codedTransaction);
        $MosaicSupplyChangeTransactionSchema = new MosaicSupplyChangeTransactionSchema;
        
        $tmp = unpack("C*",$builder->sizedByteArray());
        $builder_byte = array_slice($tmp,0,count($tmp));
        $output = $MosaicSupplyChangeTransactionSchema->serialize($builder_byte);
        return $output;
    }
}
?>